#!/usr/bin/env node
// Single source of truth for the Mirabilis version.
//
//   VERSION file  ->  the canonical Junos-style marketing string (e.g. 26.2R1-S29)
//   <semver>      ->  derived for npm/electron-builder (e.g. 26.2.29)
//
// Running this script stamps the derived semver into backend/frontend/desktop
// package.json and writes frontend/src/constants/version.js, so the three
// package manifests and the in-app version label can never disagree again.
//
// Usage:
//   node scripts/sync-version.mjs           # sync from ./VERSION
//   node scripts/sync-version.mjs 26.3R1-S1 # set a new version, then sync
//   node scripts/sync-version.mjs --check   # fail (exit 1) if anything is out of sync (for CI)

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const check = args.includes('--check');
const explicit = args.find((a) => !a.startsWith('--'));

const VERSION_FILE = join(ROOT, 'VERSION');
let marketing = explicit || readFileSync(VERSION_FILE, 'utf8').trim();
if (explicit) writeFileSync(VERSION_FILE, marketing + '\n');

// Derive a strict semver from the Junos-style tag: 26.2R1-S29 -> 26.2.29
function toSemver(v) {
  const m = v.match(/^(\d+)\.(\d+)(?:R\d+)?(?:-S(\d+))?/);
  if (!m) throw new Error(`Cannot derive semver from version "${v}"`);
  return `${m[1]}.${m[2]}.${m[3] || '0'}`;
}
const semver = toSemver(marketing);

const targets = [
  { file: 'backend/package.json', kind: 'pkg' },
  { file: 'frontend/package.json', kind: 'pkg' },
  { file: 'desktop/package.json', kind: 'pkg' },
];

let drift = false;
for (const t of targets) {
  const p = join(ROOT, t.file);
  const json = JSON.parse(readFileSync(p, 'utf8'));
  if (json.version !== semver) {
    drift = true;
    if (!check) {
      json.version = semver;
      writeFileSync(p, JSON.stringify(json, null, 2) + '\n');
      console.log(`updated ${t.file} -> ${semver}`);
    } else {
      console.error(`drift: ${t.file} is ${json.version}, expected ${semver}`);
    }
  }
}

const constPath = join(ROOT, 'frontend/src/constants/version.js');
const constBody =
  `// GENERATED by scripts/sync-version.mjs - do not edit by hand.\n` +
  `export const APP_VERSION = ${JSON.stringify(marketing)};\n` +
  `export const APP_SEMVER = ${JSON.stringify(semver)};\n`;
let constDrift = false;
try {
  constDrift = readFileSync(constPath, 'utf8') !== constBody;
} catch {
  constDrift = true;
}
if (constDrift) {
  drift = true;
  if (!check) {
    writeFileSync(constPath, constBody);
    console.log(`updated frontend/src/constants/version.js -> ${marketing} (${semver})`);
  } else {
    console.error(`drift: frontend/src/constants/version.js out of sync`);
  }
}

if (check && drift) {
  console.error('\nVersion files are out of sync. Run: node scripts/sync-version.mjs');
  process.exit(1);
}
console.log(check ? 'version: in sync' : `version: ${marketing} (semver ${semver})`);
