#!/usr/bin/env node
// Single source of truth for the Mirabilis version.
//
//   VERSION file  ->  the canonical Junos-style marketing string (e.g. 26.2R1-S29)
//   <semver>      ->  derived for npm/electron-builder (e.g. 26.2.29)
//
// Running this script stamps the derived semver into backend/frontend/desktop
// package.json and writes frontend/src/constants/version.js, so the three
// package manifests and the in-app version label can never disagree again.
//
// Usage:
//   node scripts/sync-version.mjs           # sync from ./VERSION
//   node scripts/sync-version.mjs 26.3R1-S1 # set a new version, then sync
//   node scripts/sync-version.mjs --check   # fail (exit 1) if anything is out of sync (for CI)

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const check = args.includes('--check');
const explicit = args.find((a) => !a.startsWith('--'));

const VERSION_FILE = join(ROOT, 'VERSION');
let marketing = explicit || readFileSync(VERSION_FILE, 'utf8').trim();
if (explicit) writeFileSync(VERSION_FILE, marketing + '\n');

// Derive a strict semver from the Junos-style tag: 26.2R1-S29 -> 26.2.29
function toSemver(v) {
  const m = v.match(/^(\d+)\.(\d+)(?:R\d+)?(?:-S(\d+))?/);
  if (!m) throw new Error(`Cannot derive semver from version "${v}"`);
  return `${m[1]}.${m[2]}.${m[3] || '0'}`;
}
const semver = toSemver(marketing);

const targets = [
  { file: 'backend/package.json', kind: 'pkg' },
  { file: 'frontend/package.json', kind: 'pkg' },
  { file: 'desktop/package.json', kind: 'pkg' },
];

let drift = false;
for (const t of targets) {
  const p = join(ROOT, t.file);
  const json = JSON.parse(readFileSync(p, 'utf8'));
  if (json.version !== semver) {
    drift = true;
    if (!check) {
      json.version = semver;
      writeFileSync(p, JSON.stringify(json, null, 2) + '\n');
      console.log(`updated ${t.file} -> ${semver}`);
    } else {
      console.error(`drift: ${t.file} is ${json.version}, expected ${semver}`);
    }
  }
}

const constBody =
  `// GENERATED by scripts/sync-version.mjs - do not edit by hand.\n` +
  `export const APP_VERSION = ${JSON.stringify(marketing)};\n` +
  `export const APP_SEMVER = ${JSON.stringify(semver)};\n`;
// The frontend reads its label from constants/version.js; the backend reads the
// same string for the MCP client handshake from src/version.js. Both are generated
// here so no version is ever hand-typed (and left to go stale) in source again.
const constTargets = [
  'frontend/src/constants/version.js',
  'backend/src/version.js',
];
for (const rel of constTargets) {
  const constPath = join(ROOT, rel);
  let constDrift = false;
  try {
    constDrift = readFileSync(constPath, 'utf8') !== constBody;
  } catch {
    constDrift = true;
  }
  if (constDrift) {
    drift = true;
    if (!check) {
      writeFileSync(constPath, constBody);
      console.log(`updated ${rel} -> ${marketing} (${semver})`);
    } else {
      console.error(`drift: ${rel} out of sync`);
    }
  }
}

// Stamp the human-facing version line in README.md so it can never drift from
// the canonical VERSION again (this was previously hand-maintained and went stale).
const readmePath = join(ROOT, 'README.md');
try {
  const readme = readFileSync(readmePath, 'utf8');
  const next = readme.replace(/^\*\*Version:\*\* .*$/m, `**Version:** ${marketing}  `);
  if (next !== readme) {
    drift = true;
    if (!check) {
      writeFileSync(readmePath, next);
      console.log(`updated README.md -> ${marketing}`);
    } else {
      console.error(`drift: README.md version line is out of sync`);
    }
  }
} catch { /* README is optional */ }

// Keep the version line in the proprietary LICENSE footer current too.
const licensePath = join(ROOT, 'LICENSE');
try {
  const lic = readFileSync(licensePath, 'utf8');
  const next = lic.replace(/^Version:\s+.*$/m, `Version: ${marketing}`);
  if (next !== lic) {
    drift = true;
    if (!check) {
      writeFileSync(licensePath, next);
      console.log(`updated LICENSE -> ${marketing}`);
    } else {
      console.error(`drift: LICENSE version line is out of sync`);
    }
  }
} catch { /* LICENSE is optional */ }

if (check && drift) {
  console.error('\nVersion files are out of sync. Run: node scripts/sync-version.mjs');
  process.exit(1);
}
console.log(check ? 'version: in sync' : `version: ${marketing} (semver ${semver})`);
